// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1l3_opp7D-2jX1OauJo71395MUPUWm1s',
    appId: '1:663201918739:web:911f878fce1027a65fb4e6',
    messagingSenderId: '663201918739',
    projectId: 'findly-app-de4a4',
    authDomain: 'findly-app-de4a4.firebaseapp.com',
    storageBucket: 'findly-app-de4a4.firebasestorage.app',
    measurementId: 'G-N76VKX3QEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArEnByqxCKjL7PEMOka6tMVhuIC-eMWd0',
    appId: '1:663201918739:android:a3669e08a50307d45fb4e6',
    messagingSenderId: '663201918739',
    projectId: 'findly-app-de4a4',
    storageBucket: 'findly-app-de4a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpQzP6yM5TxhBKgWKPakOsNx7Q-v1In2M',
    appId: '1:663201918739:ios:69e261d58987f4345fb4e6',
    messagingSenderId: '663201918739',
    projectId: 'findly-app-de4a4',
    storageBucket: 'findly-app-de4a4.firebasestorage.app',
    iosBundleId: 'com.example.milaoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpQzP6yM5TxhBKgWKPakOsNx7Q-v1In2M',
    appId: '1:663201918739:ios:69e261d58987f4345fb4e6',
    messagingSenderId: '663201918739',
    projectId: 'findly-app-de4a4',
    storageBucket: 'findly-app-de4a4.firebasestorage.app',
    iosBundleId: 'com.example.milaoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1l3_opp7D-2jX1OauJo71395MUPUWm1s',
    appId: '1:663201918739:web:d68b2e96ba6925965fb4e6',
    messagingSenderId: '663201918739',
    projectId: 'findly-app-de4a4',
    authDomain: 'findly-app-de4a4.firebaseapp.com',
    storageBucket: 'findly-app-de4a4.firebasestorage.app',
    measurementId: 'G-MLVP69KXT2',
  );
}
